### PR TITLE
add: Adding initial prototype of vision interpreter for ssl vision

### PR DESCRIPTION
**Pull request by FabioHuang**

### CODE REVIEW

**Review by Marcelo-Filho112 — APPROVED** [review]

**Review by AmandaOp — APPROVED** [review]

**Review by NatDuarte — APPROVED** [review]

**Comment by Menchik** [comment]
Isso tem que estar tudo dentro da pasta src e em um pacote do ros dedicado.
O nome da pasta ter vice tbm é meio redundante já que já está no repo ssl-vice.

**Comment by FabioHuang** [comment]
Untitled-2024-07-09-1554(1)

**Comment by FabioHuang** [comment]
Just in case someone wants to run the VICEs vision node, here's the commmand:

ros2 run vision visionNode

If you want to set a parameter (ip, port, ..., etc) use:

ros2 run vision visionNode --ros-args -p {parameters name}:={value} -p {parameters name}:={value}

Futhermore, vision node will publish a stream of data in a ros2 topic, to see world message published run:

ros2 topic echo /visionTopic

**Comment by FabioHuang** [comment]
This is only a functional prototype, there are still some problems that will need some attention later in development, and also a lot of room to improvements exists. Some of them are:

- The predict and update are not being used to predict future states, but rather just smooth past measurements.
- This current implementation has a run time in the milliseconds, but latency and efficiency were not the top priority, some changes will probably improve performance.
- While developing, the understanding of the problem improved, but as a result of poor planing and lack of understanding of the global scope in the beginning, the code written are not up to standards and will benefit from refactoring.

**Review by Marcelo-Filho112 — APPROVED** [review]

**Review by NatDuarte — APPROVED** [review]
There are some points for improvement, but for general purposes it seems functional

**Review by Menchik — APPROVED** [review]

**Pull request merged**
